"""Approval-path authority field manifests for ADR-0014 drift checks."""

from __future__ import annotations

from dataclasses import dataclass

from aegis.contracts.aegis_approval_receipt import ApprovalReceipt
from aegis.contracts.aegis_attestation_verifier import VerifierAdapterCertificationResult
from aegis.contracts.aegis_audit import AuditedPlan
from aegis.contracts.aegis_decision_trace import DecisionTrace
from aegis.contracts.aegis_gate import GateDecision
from aegis.contracts.aegis_intent import RawIntent
from aegis.contracts.aegis_planning import CommandPlan
from aegis.contracts.aegis_policy import (
    Capability,
    Constraint,
    Policy,
    PolicyEvaluationResult,
    PolicyRule,
    SafetyCase,
    WorldSnapshotStub,
)
from aegis.contracts.aegis_policy_admission import PolicyAdmissionRecord
from aegis.contracts.aegis_trust_policy_config import TrustPolicyConfigValidationResult
from aegis.contracts.aegis_validation import ValidationResult
from aegis.contracts.aegis_world_snapshot_admissibility import WorldSnapshotAdmissibilityResult
from aegis.contracts.aegis_world_snapshot_freshness import WorldSnapshotFreshnessResult
from aegis.contracts.aegis_world_snapshot_trust import WorldSnapshotTrustResult
from aegis.governance.aegis_context_authority import ContextAuthority
from aegis.scenarios.aegis_contracts import (
    ScenarioDefinition,
    ScenarioExpectation,
    ScenarioRunResult,
    ScenarioSuiteResult,
)


@dataclass(frozen=True, slots=True)
class AuthorityFieldManifest:
    """Static classification for fields in one approval-path contract."""

    contract_name: str
    authoritative_fields: tuple[str, ...]
    non_authoritative_fields: tuple[str, ...]
    checksum_function: str
    reason: str


@dataclass(frozen=True, slots=True)
class ApprovalPathContract:
    """Contract type paired with its static authority manifest."""

    contract_type: type[object]
    manifest: AuthorityFieldManifest


def manifest_for(
    *,
    contract_type: type[object],
    authoritative_fields: tuple[str, ...],
    non_authoritative_fields: tuple[str, ...] = (),
    checksum_function: str,
    reason: str,
) -> ApprovalPathContract:
    """Return a contract and its manifest without mutating global state."""
    return ApprovalPathContract(
        contract_type=contract_type,
        manifest=AuthorityFieldManifest(
            contract_name=contract_type.__name__,
            authoritative_fields=authoritative_fields,
            non_authoritative_fields=non_authoritative_fields,
            checksum_function=checksum_function,
            reason=reason,
        ),
    )


APPROVAL_PATH_CONTRACTS = (
    manifest_for(
        contract_type=RawIntent,
        authoritative_fields=("command", "parameters", "source_id", "priority", "context"),
        checksum_function="raw_intent_identity_checksum",
        reason="raw intent determines validation and planning authority",
    ),
    manifest_for(
        contract_type=ValidationResult,
        authoritative_fields=("is_valid", "intent", "violations"),
        checksum_function="validation_result_identity_checksum",
        reason="validation result gates planning",
    ),
    manifest_for(
        contract_type=CommandPlan,
        authoritative_fields=("plan_id", "intent", "steps"),
        checksum_function="command_plan_identity_checksum",
        reason="command plans define audited executable intent",
    ),
    manifest_for(
        contract_type=AuditedPlan,
        authoritative_fields=("plan", "audit_id", "checksum"),
        checksum_function="audited_plan_checksum",
        reason="audit records bind plans to executable checksums",
    ),
    manifest_for(
        contract_type=WorldSnapshotStub,
        authoritative_fields=(
            "snapshot_id",
            "captured_at_ms",
            "expires_at_ms",
            "source",
            "confidence",
            "facts",
            "checksum",
            "declared_capability_scope",
            "declared_fact_keys",
        ),
        checksum_function="world_snapshot_admissibility_result_checksum",
        reason="world snapshot facts and declarations gate policy evidence",
    ),
    manifest_for(
        contract_type=WorldSnapshotAdmissibilityResult,
        authoritative_fields=(
            "status",
            "reason_code",
            "world_snapshot_checksum",
            "requested_capability",
            "declared_capability_scope",
            "declared_fact_keys",
            "missing_declared_fact_keys",
            "missing_required_fact_keys",
            "undeclared_required_fact_keys",
            "checksum",
        ),
        checksum_function="world_snapshot_admissibility_result_checksum",
        reason="admissibility decides whether freshness and trust may run",
    ),
    manifest_for(
        contract_type=WorldSnapshotFreshnessResult,
        authoritative_fields=(
            "snapshot_id",
            "observed_at_ms",
            "evaluation_time_ms",
            "age_ms",
            "max_allowed_age_ms",
            "status",
            "is_fresh",
            "reason",
            "world_snapshot_checksum",
            "world_snapshot_admissibility_status",
            "world_snapshot_admissibility_reason_code",
            "world_snapshot_admissibility_result_checksum",
            "checksum",
        ),
        checksum_function="world_snapshot_freshness_checksum",
        reason="freshness is mandatory evidence for approval",
    ),
    manifest_for(
        contract_type=VerifierAdapterCertificationResult,
        authoritative_fields=(
            "status",
            "reason_code",
            "verifier_id",
            "verifier_metadata_checksum",
            "passed_vector_ids",
            "failed_vector_ids",
            "rejected_vector_ids",
            "deterministic_replay_count",
            "contract_version",
            "checksum",
        ),
        checksum_function="verifier_adapter_certification_result_checksum",
        reason="verifier certification is approval authority",
    ),
    manifest_for(
        contract_type=TrustPolicyConfigValidationResult,
        authoritative_fields=(
            "status",
            "reason_code",
            "trust_policy_checksum",
            "verifier_metadata_checksum",
            "allowed_runtime_domain",
            "capability",
            "enforce_mode",
            "checksum",
        ),
        checksum_function="trust_policy_config_validation_result_checksum",
        reason="trust policy config decides whether trust can authorize approval",
    ),
    manifest_for(
        contract_type=WorldSnapshotTrustResult,
        authoritative_fields=(
            "status",
            "reason_code",
            "world_snapshot_checksum",
            "world_snapshot_admissibility_status",
            "world_snapshot_admissibility_reason_code",
            "world_snapshot_admissibility_result_checksum",
            "evidence_envelope_checksum",
            "attestation_checksum",
            "trust_policy_checksum",
            "verifier_certification_checksum",
            "trust_policy_config_validation_checksum",
            "verifier_id",
            "verifier_metadata_checksum",
            "source_id",
            "source_type",
            "trust_domain",
            "capability",
            "verification_result_checksum",
            "evaluation_time_ms",
            "checksum",
        ),
        checksum_function="world_snapshot_trust_result_checksum",
        reason="trusted evidence is mandatory policy input",
    ),
    manifest_for(
        contract_type=Policy,
        authoritative_fields=(
            "policy_id",
            "policy_version",
            "policy_schema_version",
            "policy_checksum",
            "policy_authority",
            "effective_from_ms",
            "supersedes_policy_checksum",
            "rules",
            "capabilities",
            "default_decision",
            "metadata",
        ),
        checksum_function="policy_identity_checksum",
        reason="policy identity and content decide approval authority",
    ),
    manifest_for(
        contract_type=PolicyRule,
        authoritative_fields=("rule_id", "capability", "constraints", "description", "enabled"),
        checksum_function="policy_identity_checksum",
        reason="policy rules determine policy decisions",
    ),
    manifest_for(
        contract_type=Capability,
        authoritative_fields=("name", "version", "parameters"),
        checksum_function="policy_identity_checksum",
        reason="capabilities scope policy decisions",
    ),
    manifest_for(
        contract_type=Constraint,
        authoritative_fields=("constraint_type", "parameters", "required"),
        checksum_function="policy_identity_checksum",
        reason="constraints decide policy outcomes",
    ),
    manifest_for(
        contract_type=PolicyEvaluationResult,
        authoritative_fields=(
            "decision",
            "policy_id",
            "policy_version",
            "policy_schema_version",
            "policy_checksum",
            "policy_authority",
            "context_authority_checksum",
            "matched_rule_ids",
            "passed_constraints",
            "failed_constraints",
            "reasons",
            "world_snapshot_id",
            "world_snapshot_observed_at_ms",
            "freshness_result_checksum",
            "freshness_status",
            "world_snapshot_admissibility_status",
            "world_snapshot_admissibility_reason_code",
            "world_snapshot_admissibility_result_checksum",
            "requested_capability",
            "declared_capability_scope",
            "declared_fact_keys",
            "missing_declared_fact_keys",
            "missing_required_fact_keys",
            "undeclared_required_fact_keys",
            "world_snapshot_trust_status",
            "world_snapshot_trust_reason_code",
            "world_snapshot_trust_result_checksum",
            "evidence_envelope_checksum",
            "attestation_checksum",
            "trust_policy_checksum",
            "verifier_certification_checksum",
            "trust_policy_config_validation_checksum",
            "verifier_id",
            "verifier_metadata_checksum",
            "source_id",
            "source_type",
            "trust_domain",
        ),
        checksum_function="policy_evaluation_result_checksum",
        reason="policy evaluation result directly gates approval",
    ),
    manifest_for(
        contract_type=SafetyCase,
        authoritative_fields=(
            "safety_case_id",
            "policy_result",
            "audited_plan_id",
            "world_snapshot_id",
            "evidence",
            "plan_id",
            "plan_checksum",
            "policy_result_checksum",
            "policy_version",
            "policy_schema_version",
            "policy_checksum",
            "policy_authority",
            "context_authority_checksum",
            "world_snapshot_checksum",
            "capability_name",
            "capability_version",
            "world_snapshot_observed_at_ms",
            "freshness_result_checksum",
            "freshness_status",
            "world_snapshot_admissibility_status",
            "world_snapshot_admissibility_reason_code",
            "world_snapshot_admissibility_result_checksum",
            "requested_capability",
            "declared_capability_scope",
            "declared_fact_keys",
            "missing_declared_fact_keys",
            "missing_required_fact_keys",
            "undeclared_required_fact_keys",
            "world_snapshot_trust_status",
            "world_snapshot_trust_reason_code",
            "world_snapshot_trust_result_checksum",
            "evidence_envelope_checksum",
            "attestation_checksum",
            "trust_policy_checksum",
            "verifier_certification_checksum",
            "trust_policy_config_validation_checksum",
            "verifier_id",
            "verifier_metadata_checksum",
            "source_id",
            "source_type",
            "trust_domain",
        ),
        checksum_function="safety_case_identity_checksum",
        reason="SafetyCase explains and binds approval evidence",
    ),
    manifest_for(
        contract_type=PolicyAdmissionRecord,
        authoritative_fields=(
            "mode",
            "policy_result",
            "safety_case",
            "enforced",
            "admission_allowed",
            "reasons",
            "audit_id",
            "plan_id",
            "plan_checksum",
            "policy_id",
            "policy_version",
            "policy_schema_version",
            "policy_checksum",
            "policy_authority",
            "policy_result_checksum",
            "safety_case_id",
            "context_authority_checksum",
            "context_id",
            "caller_authority",
            "deployment_domain",
            "context_schema_version",
            "context_evaluation_time_ms",
            "world_snapshot_id",
            "world_snapshot_checksum",
            "capability_name",
            "capability_version",
            "admission_decision",
            "integrity_status",
            "exception_reason",
            "world_snapshot_observed_at_ms",
            "freshness_result_checksum",
            "freshness_status",
            "world_snapshot_admissibility_status",
            "world_snapshot_admissibility_reason_code",
            "world_snapshot_admissibility_result_checksum",
            "world_snapshot_trust_status",
            "world_snapshot_trust_reason_code",
            "world_snapshot_trust_result_checksum",
            "evidence_envelope_checksum",
            "attestation_checksum",
            "trust_policy_checksum",
            "verifier_certification_status",
            "verifier_certification_reason_code",
            "verifier_certification_checksum",
            "verifier_id",
            "verifier_metadata_checksum",
            "trust_policy_config_status",
            "trust_policy_config_reason_code",
            "trust_policy_config_validation_checksum",
            "source_id",
            "source_type",
            "trust_domain",
        ),
        checksum_function="policy_admission_record_identity_checksum",
        reason="policy admission is the final pre-gate approval authority",
    ),
    manifest_for(
        contract_type=GateDecision,
        authoritative_fields=(
            "status",
            "audit_id",
            "plan_id",
            "reasons",
            "checksum_verified",
            "audit_id_verified",
        ),
        checksum_function="gate_decision_identity_checksum",
        reason="gate decision is the final approval boundary",
    ),
    manifest_for(
        contract_type=DecisionTrace,
        authoritative_fields=("steps", "trace_checksum"),
        checksum_function="decision_trace_checksum",
        reason="decision trace proves ordered stage coverage",
    ),
    manifest_for(
        contract_type=ApprovalReceipt,
        authoritative_fields=(
            "status",
            "reason",
            "pipeline_result_id",
            "pipeline_outcome",
            "raw_intent_checksum",
            "validation_checksum",
            "plan_checksum",
            "audit_id",
            "audited_plan_checksum",
            "policy_checksum",
            "context_authority_checksum",
            "world_snapshot_checksum",
            "admissibility_checksum",
            "freshness_checksum",
            "verifier_certification_checksum",
            "trust_policy_config_checksum",
            "trust_result_checksum",
            "policy_result_checksum",
            "safety_case_checksum",
            "policy_admission_checksum",
            "gate_decision_checksum",
            "decision_trace_checksum",
            "approval_receipt_checksum",
        ),
        checksum_function="approval_receipt_checksum",
        reason="receipt is the external approval integrity boundary",
    ),
    manifest_for(
        contract_type=ContextAuthority,
        authoritative_fields=(
            "context_id",
            "request_id",
            "evaluation_time_ms",
            "caller_authority",
            "deployment_domain",
            "context_schema_version",
            "context_checksum",
        ),
        checksum_function="context_authority_checksum",
        reason="context authority makes caller authority explicit and auditable",
    ),
    manifest_for(
        contract_type=ScenarioDefinition,
        authoritative_fields=(
            "scenario_id",
            "name",
            "category",
            "intent",
            "policy",
            "world_snapshot",
            "evaluation_time_ms",
            "trust_policy_config",
            "verifier",
            "expected",
            "metadata",
            "capability",
            "world_snapshot_evidence",
            "freshness_policy",
            "runtime_trust_domain",
            "context_authority",
            "evil_twin_mutation",
        ),
        checksum_function="scenario_suite_checksum",
        reason="scenario definitions prove expected stage/category coverage",
    ),
    manifest_for(
        contract_type=ScenarioExpectation,
        authoritative_fields=(
            "expected_outcome",
            "expected_reason",
            "expected_terminal_stage",
            "required_stages",
            "forbidden_stages",
            "receipt_must_be_valid",
            "approval_receipt_required",
            "allow_late_stage_artifacts",
        ),
        checksum_function="scenario_run_result_checksum",
        reason="scenario expectations define the coverage proof",
    ),
    manifest_for(
        contract_type=ScenarioRunResult,
        authoritative_fields=(
            "scenario_id",
            "passed",
            "actual_outcome",
            "actual_reason",
            "expected_outcome",
            "expected_reason",
            "terminal_stage",
            "receipt_valid",
            "trace_valid",
            "stage_path",
            "violations",
            "pipeline_result_checksum",
            "scenario_result_checksum",
            "category",
        ),
        checksum_function="scenario_run_result_checksum",
        reason="scenario results prove pipeline behavior and receipt validation",
    ),
    manifest_for(
        contract_type=ScenarioSuiteResult,
        authoritative_fields=(
            "suite_id",
            "passed",
            "total",
            "passed_count",
            "failed_count",
            "results",
            "coverage",
            "suite_checksum",
        ),
        checksum_function="scenario_suite_checksum",
        reason="scenario suites are release coverage evidence",
    ),
)
"""Closed approval-path contract manifest registry."""

AUTHORITY_FIELD_MANIFESTS = tuple(item.manifest for item in APPROVAL_PATH_CONTRACTS)
"""Static authority field manifests consumed by contract drift checks."""


__all__ = [
    "APPROVAL_PATH_CONTRACTS",
    "AUTHORITY_FIELD_MANIFESTS",
    "ApprovalPathContract",
    "AuthorityFieldManifest",
    "manifest_for",
]
