"""Deterministic constants for Aegis Phase 1."""

ALLOWED_COMMANDS: frozenset[str] = frozenset({"move", "stop", "inspect", "wait"})

MIN_PRIORITY = 1
MAX_PRIORITY = 10

MAX_PARAMETER_DEPTH = 16
MAX_PARAMETER_KEYS = 128
MAX_STRING_LENGTH = 10_000

MAX_WAIT_DURATION_MS = 60_000

PIPELINE_VERSION = "pipeline-v1"
GATE_VERSION = "gate-v1"

ADAPTER_CONTRACT_VERSION = "execution-adapter-v1"
ROS2_MAPPING_CONTRACT_VERSION = "ros2-message-mapping-v1"
RUNTIME_DISPATCH_CONTRACT_VERSION = "runtime-dispatch-v1"
RUNTIME_BACKEND_CONTRACT_VERSION = "runtime-backend-v1"
BACKEND_REPLAY_CONTRACT_VERSION = "backend-replay-v1"

MAX_ADAPTER_STRING_LENGTH = 2_048
MAX_ADAPTER_FIELD_COUNT = 128
MAX_ADAPTER_REQUIRED_FIELD_COUNT = 64
MAX_ADAPTER_FORBIDDEN_FIELD_COUNT = 64
MAX_ADAPTER_PAYLOAD_FIELD_COUNT = 128
MAX_ADAPTER_CANONICAL_JSON_BYTES = 65_536
MAX_ROS2_QOS_DEPTH = 1_000
MAX_RUNTIME_DISPATCH_ITEMS = 128
MAX_RUNTIME_DISPATCH_PAYLOAD_BYTES = 65_536
