"""Aegis structured logging boundary.

This module provides ``AegisLogEvent`` — a pure value object — and two helper
functions for constructing and serialising log events.

**Boundary policy (ADR-0008):**

- Core pipeline functions may *construct* ``AegisLogEvent`` objects.
- Outer adapters (CLI, ROS 2 adapter, test harnesses) are responsible for
  *emitting* those events to a sink (structlog, stdout, a file, a queue).
- No global logger, no ``logging.basicConfig()``, no handler setup lives here.
- Timestamps are never generated inside this module; they are supplied by the
  caller when constructing an event.

This keeps the core deterministic: log event construction is a pure function
of its arguments.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime
from types import MappingProxyType

from aegis.contracts.json_types import FrozenJsonValue, JsonValue, freeze_json_mapping


@dataclass(frozen=True, slots=True, init=False)
class AegisLogEvent:
    """Immutable structured log event produced by the Aegis pipeline.

    Timestamps are not generated by the core — supply them from outside if
    needed (e.g. the outer adapter injects ``datetime.now(UTC)`` at emission
    time).

    Args:
        event_type: Short lowercase identifier for the event kind, e.g.
            ``"pipeline_allowed"``, ``"validation_failed"``,
            ``"gate_blocked"``.
        layer: Pipeline layer that produced the event, e.g. ``"validation"``,
            ``"gate"``, ``"pipeline"``.
        outcome: Outcome string, e.g. ``"allowed"``, ``"blocked"``,
            ``"invalid"``, ``"error"``.
        audit_id: Optional audit receipt identifier from the audit layer.
        plan_id: Optional plan identifier from the planning layer.
        reason: Optional human-readable reason string.
        timestamp: Optional caller-supplied UTC timestamp.  Never set by
            the deterministic core.
        metadata: Additional JSON-compatible key-value pairs.  Recursively
            frozen on construction.  Defaults to an empty mapping when not
            supplied.

    Raises:
        ValueError: If ``event_type``, ``layer``, or ``outcome`` are empty.
    """

    event_type: str
    layer: str
    outcome: str
    audit_id: str | None
    plan_id: str | None
    reason: str | None
    timestamp: datetime | None
    metadata: Mapping[str, FrozenJsonValue]

    def __init__(
        self,
        event_type: str,
        layer: str,
        outcome: str,
        *,
        audit_id: str | None = None,
        plan_id: str | None = None,
        reason: str | None = None,
        timestamp: datetime | None = None,
        metadata: Mapping[str, JsonValue] | None = None,
    ) -> None:
        event_type = event_type.strip()
        if event_type == "":
            raise ValueError("event_type must be non-empty")

        layer = layer.strip()
        if layer == "":
            raise ValueError("layer must be non-empty")

        outcome = outcome.strip()
        if outcome == "":
            raise ValueError("outcome must be non-empty")

        frozen_metadata: Mapping[str, FrozenJsonValue] = (
            freeze_json_mapping(metadata) if metadata is not None else MappingProxyType({})
        )

        object.__setattr__(self, "event_type", event_type)
        object.__setattr__(self, "layer", layer)
        object.__setattr__(self, "outcome", outcome)
        object.__setattr__(self, "audit_id", audit_id)
        object.__setattr__(self, "plan_id", plan_id)
        object.__setattr__(self, "reason", reason)
        object.__setattr__(self, "timestamp", timestamp)
        object.__setattr__(self, "metadata", frozen_metadata)


def make_log_event(
    event_type: str,
    layer: str,
    outcome: str,
    *,
    audit_id: str | None = None,
    plan_id: str | None = None,
    reason: str | None = None,
    timestamp: datetime | None = None,
    metadata: Mapping[str, JsonValue] | None = None,
) -> AegisLogEvent:
    """Construct an ``AegisLogEvent`` from explicit arguments.

    This is the preferred constructor when building log events inside pipeline
    functions.  All arguments are explicit — no environment reads, no
    auto-generated timestamps.

    Args:
        event_type: Short lowercase event identifier.
        layer: Pipeline layer name.
        outcome: Outcome string.
        audit_id: Optional audit receipt identifier.
        plan_id: Optional plan identifier.
        reason: Optional human-readable reason.
        timestamp: Optional caller-supplied UTC datetime.
        metadata: Additional JSON-compatible metadata mapping.

    Returns:
        A frozen ``AegisLogEvent``.
    """
    return AegisLogEvent(
        event_type=event_type,
        layer=layer,
        outcome=outcome,
        audit_id=audit_id,
        plan_id=plan_id,
        reason=reason,
        timestamp=timestamp,
        metadata=metadata,
    )


def serialise_log_event(event: AegisLogEvent) -> dict[str, object]:
    """Convert an ``AegisLogEvent`` to a JSON-compatible plain dict.

    The returned dict is suitable for passing to a structlog processor or
    serialising with ``json.dumps``.  The ``timestamp`` field is serialised
    as an ISO-8601 string when present.

    Args:
        event: The log event to serialise.

    Returns:
        A plain ``dict[str, object]`` with all fields represented.
    """
    return {
        "event_type": event.event_type,
        "layer": event.layer,
        "outcome": event.outcome,
        "audit_id": event.audit_id,
        "plan_id": event.plan_id,
        "reason": event.reason,
        "timestamp": event.timestamp.isoformat() if event.timestamp is not None else None,
        "metadata": dict(event.metadata),
    }
